# GitHub reusable workflow for deploying a local Dockerfile to Google Container
# Registry or Google Artifact Registry.

on:
  workflow_call:
    inputs:
      project-id:
        description: ID of the GCP project where the container should be pushed to
        required: true
        type: string
      region-zone:
        description: Region zone of the GCP resources
        required: true
        type: string
      environment:
        description: Build and deploy environment (i.e. for GitHub deployment, Sentry release, etc.)
        required: false
        type: string
      image:
        description: Docker image to deploy
        required: true
        type: string
      cluster-service-label:
        description: '`service` label for matching GKE clusters'
        required: true
        type: string
      k8s-namespace:
        description: Kubernetes namespace in the GKE cluster to deploy to.
        required: false
        type: string
      k8s-app-name:
        description: Kubernetes app name used as the container label.
        required: true
        type: string
      k8s-deployment-name:
        description: Kubernetes deployment to update at the end of the deployment.
        required: true
        type: string
      workload-identity-provider:
        description: Workload Identity Provider name, i.e. `projects/123456789/locations/global/workloadIdentityPools/my-pool/providers/my-provider`
        required: true
        type: string
      service-account:
        description: GCP service account to impersonate by this Workload Identity
        required: true
        type: string
    secrets:
      gh-access-token:
        description: GitHub access token for accessing private repositories
        required: true
jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    permissions:
      id-token: write
    environment: ${{ inputs.environment }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: recursive
          token: ${{ secrets.gh-access-token }}
      - name: Authenticate Google Cloud
        id: auth
        uses: google-github-actions/auth@v1
        with:
          token_format: access_token
          workload_identity_provider: ${{ inputs.workload-identity-provider }}
          service_account: ${{ inputs.service-account }}
      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v1
      - name: Update clusters
        env:
          PROJECT_ID: ${{ inputs.project-id }}
          REGION_ZONE: ${{ inputs.region-zone }}
          SERVICE_LABEL: ${{ inputs.cluster-service-label}}
          ENVIRONMENT_LABEL: ${{ inputs.environment}}
          IMAGE: ${{ inputs.image }}
          K8S_NAMESPACE: ${{ inputs.k8s-namespace }}
          K8S_APP_NAME: ${{ inputs.k8s-app-name }}
          K8S_DEPLOYMENT_NAME: ${{ inputs.k8s-deployment-name }}
        run: |-
          clusters=$(gcloud container clusters list \
            --project=$PROJECT_ID \
            --zone=$REGION_ZONE \
            --filter="nodeConfig.labels.service=${SERVICE_LABEL} AND nodeConfig.labels.environment=${ENVIRONMENT_LABEL}" \
            | awk 'NR >= 2 {print $1}' \
            | sed -n -e 'H;${x;s/\n/,/g;s/^,//;p;}')

          echo "GKE clusters: ${clusters}" >> $GITHUB_STEP_SUMMARY
          echo "Preparing to deploy ${IMAGE} to Kubernetes cluster(s)..."

          if [ ! -z $clusters ]; then
            for cluster in $(echo $clusters | sed "s/,/ /g")
            do
              if [ ! -z $cluster ]; then
                echo -e "Deploying to ${cluster}... deployment=${K8S_DEPLOYMENT_NAME}, app=${K8S_APP_NAME}, image=${IMAGE}, namespace=${K8S_NAMESPACE}"

                # gcloud --quiet config set project $PROJECT_ID
                # gcloud --quiet config set compute/zone $REGION_ZONE
                gcloud --quiet config set container/cluster $cluster
                gcloud --quiet container clusters get-credentials $cluster
                kubectl set image deployment/$K8S_DEPLOYMENT_NAME $K8S_APP_NAME=$IMAGE --namespace=$K8S_NAMESPACE

                echo -e "Deploying to ${cluster}... OK"
              fi
            done
          else
            echo -e "No Kubernetes cluster(s) provided, skipping operation"
          fi
