# GitHub reusable workflow for deploying a local Dockerfile to Google Container
# Registry or Google Artifact Registry.

on:
  workflow_call:
    inputs:
      region-zone:
        description: Region zone of the GCP resources
        required: true
        type: string
      environment:
        description: Build and deploy environment (i.e. for GitHub deployment, Sentry release, etc.)
        required: false
        type: string
      image:
        description: Docker image to deploy
        required: true
        type: string
      match-labels:
        description: Comma-delimited labels to match when searching for clusters to deploy (i.e. "service=foo,environment=bar")
        required: false
        type: string
      k8s-namespace:
        description: Kubernetes namespace in the GKE cluster to deploy to.
        required: false
        type: string
      k8s-container:
        description: Kubernetes container name.
        required: true
        type: string
      k8s-deployment:
        description: Kubernetes deployment to update at the end of the deployment.
        required: true
        type: string
    secrets:
      gh-access-token:
        description: GitHub access token for checking out private repos
        required: true
      workload-identity-provider:
        description: Workload Identity Provider name, i.e. `projects/123456789/locations/global/workloadIdentityPools/my-pool/providers/my-provider`
        required: true
      service-account:
        description: GCP service account to impersonate by the current Workload Identity
        required: true
jobs:
  deploy:
    name: Kubernetes
    runs-on: ubuntu-latest
    permissions:
      id-token: write
    environment: ${{ inputs.environment }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: recursive
          token: ${{ secrets.gh-access-token }}
      - name: Authenticate Google Cloud
        id: auth
        uses: google-github-actions/auth@v1
        with:
          token_format: access_token
          workload_identity_provider: ${{ secrets.workload-identity-provider }}
          service_account: ${{ secrets.service-account }}
      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v1
        with:
          install_components: gke-gcloud-auth-plugin
          project_id: ${{ steps.auth.outputs.project_id }}
      - name: Update clusters
        env:
          REGION_ZONE: ${{ inputs.region-zone }}
          IMAGE: ${{ inputs.image }}
          MATCH_LABELS: ${{ inputs.match-labels }}
          K8S_NAMESPACE: ${{ inputs.k8s-namespace }}
          K8S_CONTAINER: ${{ inputs.k8s-container }}
          K8S_DEPLOYMENT: ${{ inputs.k8s-deployment }}
          USE_GKE_GCLOUD_AUTH_PLUGIN: True
        run: |-
          labels=($(echo $MATCH_LABELS | sed "s/,/ /g"))
          filter=$(printf " AND nodeConfig.labels.%s" "${labels[@]}")
          clusters=$(gcloud container clusters list \
            --zone=$REGION_ZONE \
            --filter="${filter:5}" \
            | awk 'NR >= 2 {print $1}' \
            | sed -n -e 'H;${x;s/\n/,/g;s/^,//;p;}')

          echo "Preparing to deploy ${IMAGE} to Kubernetes cluster(s)..."

          if [ ! -z $clusters ]; then
            for cluster in $(echo $clusters | sed "s/,/ /g")
            do
              if [ ! -z $cluster ]; then
                echo -e "Deploying to ${cluster}... deployment=${K8S_DEPLOYMENT}, app=${K8S_CONTAINER}, image=${IMAGE}, namespace=${K8S_NAMESPACE}"

                gcloud container clusters get-credentials $cluster --zone=$REGION_ZONE --quiet
                kubectl set image deployment/$K8S_DEPLOYMENT $K8S_CONTAINER=$IMAGE --namespace=$K8S_NAMESPACE

                echo -e "Deploying to ${cluster}... OK"
                echo "- Updated \`$K8S_CONTAINER\` to \`${IMAGE}\` in \`deployment/$K8S_DEPLOYMENT\` for cluster \`${cluster}\`" >> $GITHUB_STEP_SUMMARY
              fi
            done
          else
            echo -e "No Kubernetes cluster(s) found, skipping deploy"
            echo "No Kubernetes cluster(s) found, deployment skipped." >> $GITHUB_STEP_SUMMARY
          fi
