# GitHub reusable workflow for building and testing a local Dockerfile to Google
# Container Registry or Google Artifact Registry.

on:
  workflow_call:
    inputs:
      project-id:
        required: true
        type: string
      environment:
        required: false
        type: string
    secrets:
      gh-access-token:
        description: GitHub access token for accessing private repositories
        required: true
      sentry-auth-token:
        required: false
jobs:
  a:
    name: A
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: recursive
          token: ${{ secrets.gh-access-token }}
      - name: Test
        run: |-
          echo ${{ inputs.environment }}, ${{ inputs.environment == '' }}
          echo ${{ vars.GCP_PROJECT }}, ${{ vars.GCP_PROJECT == '' }}
          echo ${{ inputs.project-id }}, ${{ inputs.project-id == '' }}
          echo ${{ secrets.sentry-auth-token }}, ${{ secrets.sentry-auth-token == '' }}
          pwd
          sh scripts/foo.sh
  c:
    name: C
    uses: ./.github/workflows/test2-build.yml
  b:
    name: B
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    if: ${{ inputs.environment }}
    steps:
      - name: Test
        run: |-
          echo "HELLO, WORLD"
